import {
  Property,
  PropertyStatus,
  Advert,
  Platform,
  DashboardStats,
  ActivityItem,
} from "./types";

// Helper to create dates relative to now
function daysAgo(days: number): Date {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
}

function hoursAgo(hours: number): Date {
  const date = new Date();
  date.setHours(date.getHours() - hours);
  return date;
}

export const mockProperties: Property[] = [
  {
    id: "prop-1",
    address: "Keizersgracht 482",
    postalCode: "1017 EG",
    city: "Amsterdam",
    price: 845000,
    squareMeters: 142,
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    buildYear: 1890,
    energyLabel: "A",
    status: PropertyStatus.Published,
    images: ["/images/property-1a.jpg", "/images/property-1b.jpg"],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(2),
  },
  {
    id: "prop-2",
    address: "Oudegracht 156",
    postalCode: "3511 AZ",
    city: "Utrecht",
    price: 525000,
    squareMeters: 98,
    rooms: 4,
    bedrooms: 2,
    bathrooms: 1,
    buildYear: 1920,
    energyLabel: "B",
    status: PropertyStatus.Generated,
    images: ["/images/property-2a.jpg"],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: "prop-3",
    address: "Witte de Withstraat 38",
    postalCode: "3012 BR",
    city: "Rotterdam",
    price: 375000,
    squareMeters: 85,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    buildYear: 2005,
    energyLabel: "A+",
    status: PropertyStatus.Published,
    images: ["/images/property-3a.jpg", "/images/property-3b.jpg"],
    createdAt: daysAgo(21),
    updatedAt: daysAgo(5),
  },
  {
    id: "prop-4",
    address: "Lange Voorhout 74",
    postalCode: "2514 EH",
    city: "Den Haag",
    price: 695000,
    squareMeters: 120,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    buildYear: 1875,
    energyLabel: "C",
    status: PropertyStatus.Draft,
    images: ["/images/property-4a.jpg"],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "prop-5",
    address: "Herengracht 320",
    postalCode: "1016 CE",
    city: "Amsterdam",
    price: 725000,
    squareMeters: 115,
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    buildYear: 1910,
    energyLabel: "B",
    status: PropertyStatus.Generated,
    images: ["/images/property-5a.jpg", "/images/property-5b.jpg"],
    createdAt: daysAgo(10),
    updatedAt: hoursAgo(8),
  },
  {
    id: "prop-6",
    address: "Mariaplaats 12",
    postalCode: "3511 LH",
    city: "Utrecht",
    price: 450000,
    squareMeters: 78,
    rooms: 3,
    bedrooms: 1,
    bathrooms: 1,
    buildYear: 1955,
    energyLabel: "D",
    status: PropertyStatus.Draft,
    images: [],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "prop-7",
    address: "Noordeinde 58",
    postalCode: "2514 GL",
    city: "Den Haag",
    price: 550000,
    squareMeters: 95,
    rooms: 4,
    bedrooms: 2,
    bathrooms: 1,
    buildYear: 1935,
    energyLabel: "A++",
    status: PropertyStatus.Published,
    images: ["/images/property-7a.jpg", "/images/property-7b.jpg"],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(10),
  },
  {
    id: "prop-8",
    address: "Coolsingel 42",
    postalCode: "3011 AD",
    city: "Rotterdam",
    price: 299000,
    squareMeters: 65,
    rooms: 3,
    bedrooms: 1,
    bathrooms: 1,
    buildYear: 2018,
    energyLabel: "A+++",
    status: PropertyStatus.Generated,
    images: ["/images/property-8a.jpg"],
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(3),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalProperties: 24,
  generatedThisMonth: 12,
  published: 8,
  averageGenerationTime: "2,4s",
  totalPropertiesTrend: 12.5,
  generatedThisMonthTrend: 8.3,
  publishedTrend: 15.0,
  averageGenerationTimeTrend: -5.2,
};

export const mockActivityFeed: ActivityItem[] = [
  {
    id: "act-1",
    type: "generated",
    propertyAddress: "Coolsingel 42, Rotterdam",
    propertyId: "prop-8",
    timestamp: hoursAgo(3),
  },
  {
    id: "act-2",
    type: "edited",
    propertyAddress: "Herengracht 320, Amsterdam",
    propertyId: "prop-5",
    timestamp: hoursAgo(8),
  },
  {
    id: "act-3",
    type: "published",
    propertyAddress: "Keizersgracht 482, Amsterdam",
    propertyId: "prop-1",
    platform: Platform.Funda,
    timestamp: daysAgo(2),
  },
  {
    id: "act-4",
    type: "generated",
    propertyAddress: "Oudegracht 156, Utrecht",
    propertyId: "prop-2",
    timestamp: daysAgo(1),
  },
  {
    id: "act-5",
    type: "published",
    propertyAddress: "Witte de Withstraat 38, Rotterdam",
    propertyId: "prop-3",
    platform: Platform.Pararius,
    timestamp: daysAgo(5),
  },
  {
    id: "act-6",
    type: "edited",
    propertyAddress: "Keizersgracht 482, Amsterdam",
    propertyId: "prop-1",
    timestamp: daysAgo(3),
  },
  {
    id: "act-7",
    type: "generated",
    propertyAddress: "Herengracht 320, Amsterdam",
    propertyId: "prop-5",
    timestamp: daysAgo(4),
  },
  {
    id: "act-8",
    type: "published",
    propertyAddress: "Noordeinde 58, Den Haag",
    propertyId: "prop-7",
    platform: Platform.Jaap,
    timestamp: daysAgo(10),
  },
  {
    id: "act-9",
    type: "generated",
    propertyAddress: "Witte de Withstraat 38, Rotterdam",
    propertyId: "prop-3",
    timestamp: daysAgo(6),
  },
  {
    id: "act-10",
    type: "edited",
    propertyAddress: "Noordeinde 58, Den Haag",
    propertyId: "prop-7",
    timestamp: daysAgo(11),
  },
  {
    id: "act-11",
    type: "generated",
    propertyAddress: "Noordeinde 58, Den Haag",
    propertyId: "prop-7",
    timestamp: daysAgo(12),
  },
];

export const mockAdverts: Advert[] = [
  {
    id: "adv-1",
    propertyId: "prop-1",
    title: "Stijlvol grachtenpand aan de Keizersgracht",
    description:
      "Dit prachtige grachtenpand uit 1890 combineert authentieke details met modern comfort. De woning beschikt over originele ornamenten, hoge plafonds en grote ramen die zorgen voor een overvloed aan natuurlijk licht. De volledig gerenoveerde keuken en badkamers bieden alle hedendaagse gemakken. Gelegen aan een van de mooiste grachten van Amsterdam, met winkels, restaurants en het Rijksmuseum op loopafstand.",
    features: [
      "Originele ornamenten en schouwen",
      "Volledig gerenoveerde keuken met inbouwapparatuur",
      "Twee luxe badkamers met vloerverwarming",
      "Uitzicht over de Keizersgracht",
      "Energielabel A — uitstekend geïsoleerd",
    ],
    platform: Platform.Funda,
    createdAt: daysAgo(5),
  },
  {
    id: "adv-2",
    propertyId: "prop-2",
    title: "Karakteristiek werfkelderwoningen aan de Oudegracht",
    description:
      "Unieke woning aan de beroemde Oudegracht in het hart van Utrecht. Deze charmante woning uit 1920 biedt een bijzondere woervaring met directe toegang tot de werf. De lichte woonkamer met originele balkenplafonds en de moderne open keuken maken dit tot een droomwoning voor liefhebbers van stadswonen met karakter.",
    features: [
      "Directe toegang tot de Oudegracht-werf",
      "Originele balkenplafonds",
      "Moderne open keuken",
      "Midden in het centrum van Utrecht",
    ],
    platform: Platform.Pararius,
    createdAt: daysAgo(3),
  },
  {
    id: "adv-3",
    propertyId: "prop-3",
    title: "Modern appartement in het bruisende Rotterdam",
    description:
      "Licht en ruim appartement in het populaire Witte de Withkwartier. Dit moderne appartement uit 2005 is perfect voor wie wil genieten van het stadsleven. De open woonkeuken, het ruime balkon en de nabijheid van culturele hotspots zoals het Museumpark maken deze woning ideaal voor jong professionals en stellen.",
    features: [
      "Ruim balkon op het zuiden",
      "Open woonkeuken met kookeiland",
      "Energielabel A+ — zeer energiezuinig",
      "Op loopafstand van Museumpark en Erasmusbrug",
      "Eigen parkeerplaats in de garage",
    ],
    platform: Platform.Funda,
    createdAt: daysAgo(8),
  },
  {
    id: "adv-4",
    propertyId: "prop-5",
    title: "Elegant herenhuis aan de Herengracht",
    description:
      "Sfeervol herenhuis uit 1910 aan de prestigieuze Herengracht. Deze woning straalt klasse uit met zijn hoge plafonds, sierlijke gevel en prachtige erker. De combinatie van authentieke elementen en moderne voorzieningen maakt dit een unieke kans in het hart van Amsterdam. Twee royale badkamers en een zonnige achtertuin completeren het geheel.",
    features: [
      "Monumentale gevel met erker",
      "Hoge plafonds met stucwerk",
      "Twee luxe badkamers",
      "Zonnige achtertuin op het westen",
      "Kelder met bergruimte",
    ],
    platform: Platform.Jaap,
    createdAt: daysAgo(2),
  },
  {
    id: "adv-5",
    propertyId: "prop-7",
    title: "Gerenoveerde stadswoning nabij het Noordeinde",
    description:
      "Prachtig gerenoveerde stadswoning uit 1935 in het gewilde Noordeinde-kwartier van Den Haag. Dankzij de recente renovatie beschikt deze woning over energielabel A++ en alle moderne gemakken, terwijl het oorspronkelijke karakter behouden is gebleven. De locatie nabij het Paleis Noordeinde, de Passage en het strand van Scheveningen maakt deze woning bijzonder aantrekkelijk.",
    features: [
      "Energielabel A++ na volledige renovatie",
      "Oorspronkelijke details behouden",
      "Nabij Paleis Noordeinde en de Passage",
      "15 minuten fietsen naar Scheveningen",
    ],
    platform: Platform.Funda,
    createdAt: daysAgo(15),
  },
  {
    id: "adv-6",
    propertyId: "prop-8",
    title: "Nieuwbouwappartement aan de Coolsingel",
    description:
      "Stijlvol nieuwbouwappartement uit 2018 aan de volledig vernieuwde Coolsingel. Dit compacte maar slim ingedeelde appartement biedt alles wat een moderne stadsbewoner nodig heeft. Met energielabel A+++ zijn de energiekosten minimaal. De centrale ligging bij Rotterdam Centraal en de Markthal maakt dit de perfecte stadswoning.",
    features: [
      "Energielabel A+++ — bijna energieneutraal",
      "Slimme indeling met veel bergruimte",
      "Aan de vernieuwde Coolsingel",
      "5 minuten lopen naar Rotterdam Centraal",
      "Gemeenschappelijk dakterras",
    ],
    platform: Platform.Pararius,
    createdAt: hoursAgo(4),
  },
];
